services:
  - type: web
    name: telegram-netflix-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TG_API_ID
        value: your_api_id_here
      - key: TG_API_HASH
        value: your_api_hash_here
    autoDeploy: true
